/*
 * Programa criado por Luiz Rogério para agiliar processo diario da empresa
 * Setor T.I. Rede São Paulo
 * Desenvolvido em Java 
 * Precisa melhorar mais devagar e sempre 
 */
package atualiza;

import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;
import javax.swing.JOptionPane;

/**
 *
 * @author ADM-Suporte
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
        setIcon();
        setResizable(false);
        JOptionPane.showMessageDialog(null, "Sejam bem-vindo ao Atualiza\n clique no botão desejado !\n\n"
                + "Primeira vez utilize a tecla sobre "); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Up = new javax.swing.JButton();
        btn_terminal = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        title_princi = new javax.swing.JLabel();
        title_2 = new javax.swing.JLabel();
        btn_ArqColetor = new javax.swing.JButton();
        btn_Gerar = new javax.swing.JButton();
        btn_Copy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_caixa_principal = new javax.swing.JLabel();
        btn_sobre = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATUALIZA V2");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        btn_Up.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        btn_Up.setForeground(new java.awt.Color(0, 16, 133));
        btn_Up.setText("UP EAN");
        btn_Up.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Up.setBorderPainted(false);
        btn_Up.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Up.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Up);
        btn_Up.setBounds(20, 180, 110, 40);

        btn_terminal.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        btn_terminal.setForeground(new java.awt.Color(0, 16, 133));
        btn_terminal.setText("Terminal");
        btn_terminal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_terminal.setBorderPainted(false);
        btn_terminal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_terminal.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_terminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_terminal);
        btn_terminal.setBounds(320, 180, 120, 40);

        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atualiza/Cancel.png"))); // NOI18N
        btn_sair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_sair.setBorderPainted(false);
        btn_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sair.setFocusCycleRoot(true);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sair);
        btn_sair.setBounds(500, 190, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atualiza/marca-com-elipse.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 0, 100, 70);

        title_princi.setFont(new java.awt.Font("STIX", 0, 36)); // NOI18N
        title_princi.setForeground(new java.awt.Color(0, 16, 133));
        title_princi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_princi.setText("Hiper São Paulo");
        getContentPane().add(title_princi);
        title_princi.setBounds(-10, 60, 330, 50);

        title_2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        title_2.setForeground(new java.awt.Color(0, 16, 133));
        title_2.setText("T.I. Rede São Paulo");
        getContentPane().add(title_2);
        title_2.setBounds(90, 100, 120, 20);

        btn_ArqColetor.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        btn_ArqColetor.setForeground(new java.awt.Color(0, 16, 133));
        btn_ArqColetor.setText("ARQ Col.");
        btn_ArqColetor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ArqColetor.setBorderPainted(false);
        btn_ArqColetor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ArqColetor.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_ArqColetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ArqColetorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ArqColetor);
        btn_ArqColetor.setBounds(160, 180, 140, 40);

        btn_Gerar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 13)); // NOI18N
        btn_Gerar.setForeground(new java.awt.Color(0, 16, 133));
        btn_Gerar.setText("Gerar ETQ");
        btn_Gerar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Gerar.setBorderPainted(false);
        btn_Gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GerarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Gerar);
        btn_Gerar.setBounds(360, 70, 130, 40);

        btn_Copy.setFont(new java.awt.Font("Courier 10 Pitch", 1, 13)); // NOI18N
        btn_Copy.setForeground(new java.awt.Color(0, 16, 133));
        btn_Copy.setText("Copy ETQ");
        btn_Copy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Copy.setBorderPainted(false);
        btn_Copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CopyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Copy);
        btn_Copy.setBounds(360, 120, 130, 40);

        jLabel3.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 16, 133));
        jLabel3.setText("Função para etq. eletrônica");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 40, 200, 20);

        lbl_caixa_principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lbl_caixa_principal);
        lbl_caixa_principal.setBounds(320, 60, 210, 110);

        btn_sobre.setText("Sobre");
        btn_sobre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 255), null, null));
        btn_sobre.setBorderPainted(false);
        btn_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sobreActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sobre);
        btn_sobre.setBounds(460, 10, 60, 21);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atualiza/wallpaper2.jpg"))); // NOI18N
        getContentPane().add(background1);
        background1.setBounds(-20, -20, 620, 290);

        setSize(new java.awt.Dimension(558, 267));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpActionPerformed
//Ação para ativar arquivo batsetResizable(false);
    
     btn_Up.setEnabled(true);
    //JOptionPane.showMessageDialog(null, "Update concluido com sucesso!"); 
    String comando = "C:\\Atualiza\\startupdate.bat";
    try 
    {
     Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+comando); 
    }   catch (java.io.IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    int opcao = JOptionPane.showConfirmDialog(null,"UPDATE concluido com sucesso,\n      "
            + "             deseja sair?","UPDATE",JOptionPane.YES_OPTION);
    
     if(opcao == JOptionPane.YES_OPTION){
     System.exit(0);
     }
    
    
        //System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_btn_UpActionPerformed

    private void btn_terminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminalActionPerformed
    
        btn_terminal.setEnabled(false);
     
    //JOptionPane.showMessageDialog(null, "Update concluido com sucesso!"); 
    
   
      String comando = "C:\\Atualiza\\startX.bat";
      try 
    {
     Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+comando); 
    }   catch (java.io.IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    int opcao = JOptionPane.showConfirmDialog(null,"    Processo concluido com Sucesso,\nclique em sim para fechar o programa, \n"
            + "              ou não para voltar ","Terminal ",JOptionPane.YES_OPTION);
    
     if(opcao == JOptionPane.YES_OPTION){
     System.exit(0);
     }  // TODO add your handling code here:
    }//GEN-LAST:event_btn_terminalActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
         System.exit(0); 
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_ArqColetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ArqColetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ArqColetorActionPerformed

    private void btn_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sobreActionPerformed
        // Chamando tela sobre
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_btn_sobreActionPerformed

    private void btn_GerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GerarActionPerformed
        // TODO add your handling code here:
        btn_Gerar.setEnabled(false);
        
        String comando = "C:\\Atualiza\\etiquetaeletronica\\gera_script_arquivo_i1_hoje_hiper.bat";
              try 
    {
     Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+comando); 
    }   catch (java.io.IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    int opcao = JOptionPane.showConfirmDialog(null,"Ao termino do processo, click em Ok,\n       logo após click em Copy ETQ  ","Processando... ",JOptionPane.CLOSED_OPTION);
    
     if(opcao == JOptionPane.OK_OPTION){
     //System.exit(0);
     }
    }//GEN-LAST:event_btn_GerarActionPerformed

    private void btn_CopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CopyActionPerformed
        // TODO add your handling code here:
        btn_Copy.setEnabled(false);
        
        String comando = "C:\\Atualiza\\copy_m1.bat";
              try 
    {
     Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+comando); 
    }   catch (java.io.IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    int opcao = JOptionPane.showConfirmDialog(null,"            Copiado com sucesso,\n   Clique em SIM para fechar o programa! \n                 ou não para voltar! ","Copiando... ",JOptionPane.YES_OPTION);
    
     if(opcao == JOptionPane.YES_OPTION){
     System.exit(0);
     }
    }//GEN-LAST:event_btn_CopyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Principal().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background1;
    private javax.swing.JButton btn_ArqColetor;
    private javax.swing.JButton btn_Copy;
    private javax.swing.JButton btn_Gerar;
    private javax.swing.JButton btn_Up;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_sobre;
    private javax.swing.JButton btn_terminal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_caixa_principal;
    private javax.swing.JLabel title_2;
    private javax.swing.JLabel title_princi;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
